# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-06 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=64)),
                ('pw', models.CharField(max_length=64)),
                ('dt', models.DateField()),
            ],
            options={
                'db_table': 'test12',
                'verbose_name': '\u7b2c\u4e00\u4e2atest',
                'verbose_name_plural': '\u7b2c\u4e00\u4e2atest',
            },
        ),
    ]
